version: "3.9"
services:
  web:
    container_name: projeck-server
    image: evolvingsoftware/business-management-api
    ports:
      - "8844:8844"
  mongodb:
    container_name: projectk-mongodb
    image: mongo:5.0
    ports:
      - "27017:27017"
  redis:
    container_name: projectk-redis
    ports:
      - "6379:6379"
    image: redis:5.0
    