version: "3.9"
services:
  web:
    container_name: evolving_solutions_url_shortener_api
    image: evolvingsoftware/evolving_solutions_url_shortener_api:alpha
    ports:
      - "8844:8844"
  mongodb:
    container_name: mongodb
    image: mongo:5.0
    ports:
      - "27017:27017"
    # add user and password to mongodb
    environment:
      - MONGO_INITDB_DATABASE=evolving_solutions